/**
 * Configuration file for Oncade integration
 * This file is generated by the setup script and should not be edited directly
 */

const config = {
    oncade: {
        apiKey: 'YOUR_API_KEY_HERE',
        gameId: 'YOUR_GAME_ID_HERE'
    }
};

// In a browser environment, we can't directly access process.env
// Instead, we'll use a global variable that can be set by the server
if (typeof window !== 'undefined' && window.ENV) {
    config.oncade.apiKey = window.ENV.ONCADE_API_KEY || config.oncade.apiKey;
    config.oncade.gameId = window.ENV.ONCADE_GAME_ID || config.oncade.gameId;
}

export default config; 